analytics:
  google:
    id: UA-100531691-1
  piwik:
    id: 1
    api:
      url: https://vps.irockbunny.com/analytics/?callback=?
      token: 628da6a2333d34e7b22be3b6bf729821

repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai

name: 北邮人导航 · BYR-Navi
alias: 北邮人导航
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: A Navigation Website for BYR
keywords: 北邮人导航, BYR-Navi, BYR, BUPT, Navi, Navigation
url: http://byr-navi.com
contact: contact[at]irockbunny[dot]com

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor